openapi: "3.0.0"
info:
  title: "Bitcoin Data"
  version: "1.0.0"
paths:
  /bitcoin/info:
    get:
      summary: "Get Bitcoin data from the node"
      operationId: "getBitcoinData"
      responses:
        '200':
          description: "Bitcoin data"
          content:
            application/json:
              schema:
                type: object
                properties:
                  blockHeight:
                    type: integer
                    description: "Current block height"
                  blockchainInfo:
                    type: object
                    description: "Information about the blockchain"
                  networkInfo:
                    type: object
                    description: "Information about the Bitcoin network"
